spring:
  application:
    name: multas-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/multa_manager
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
